%
% Script to be run for executing all reconstruction simulations for
% creation of ALMT phase diagram. One particular phase diagram and desired 
% parameters should be selected and the script will loop over all
% parameteres saving the reconstructed and original images in separate
% files.
%
% Jakob S. Joergensen (jakj@dtu.dk), 2014.
%

clear
clc

%% Which ALMT phase diagram to construct raw simulation data for?

% Choose 1-6 to generate one of the 6 ALMT phase diagrams from the paper:

run_func_choice = 1;

run_func_list = {...
    'run_sim_func_almt_signedspikes_fanbeam_equi_offset20',...
    'run_sim_func_almt_signedspikes_gaussian',...
    'run_sim_func_almt_spikes_fanbeam_equi_offset20',...
    'run_sim_func_almt_spikes_gaussian',...
    'run_sim_func_almt_altprojisotv_fanbeam_equi_offset20',...
    'run_sim_func_almt_altprojisotv_gaussian'};
run_func = run_func_list{run_func_choice}

%% Includes

% MOSEK MUST BE INSTALLED AND ON THE MATLAB PATH
% addpath to mosek

addpath ../ext/parobj/
addpath ../run_funcs/

%% set up pars

% Image side length
N = 64;

% Relative sparsities
spfrac = 0.025:0.025:(1-0.025);

% Random seeds
seed = 0:99;

% Number of angles. Include 0 to save original image.
numangles = 0:26;

% Set up the parameter object specifying which parameters to loop over.
po = parobj;
po.setValues( {N, spfrac, seed, numangles} )
po.setNames( {'N', 'spfrac', 'seed', 'numangles'} )
po.setTypes( {'%d', '%f', '%d', '%d'} );
po.setStub( 'res' );
po.buildArray()

%% Run sweep over all parameters

% Do not use the automatic savefilename generated by parsweep because the
% filename is set up inside the simulation.
use_parsweep_auto_savefilename = false;

% Run all for all parameters
po.parsweep(run_func,use_parsweep_auto_savefilename)
